name: Daily AQI Trigger

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC (11:30 AM IST)
  workflow_dispatch:   

jobs:
  ping_api:
    runs-on: ubuntu-latest

    steps:
      - name: Hit FastAPI /predict endpoint
        run: |
          curl --silent --show-error --fail https://aqi-backend-itir.onrender.com/predict
